
name: pr-check

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: echo something
        run: echo "hello world"

  linux:
    name: Linux
    runs-on: ubuntu-24.04
    steps:
      - name: echo something
        run: echo "hello world"

  lint-format:
    name: linter, formatters
    runs-on: ubuntu-24.04
    steps:
      - name: echo something
        run: echo "hello world"
    
